---
- hosts: redhat-servers
  become: true
  vars:
    nginx_user: nginx
  roles:
   - epel
   - nginx
   - Grafana
   - Update_Certs
   - Prometheus

- hosts: debian-servers
  become: true
  vars:
    nginx_user: www-data
  roles:
   - nginx
   - Grafana
   - Update_Certs
   - Prometheus